LOCAL_DATABASE:
    DATABASE_NAME: 'Fitness_database'
    HOST: 'localhost'
    PORT: '3306'
    USER_NAME: 'root'
    PASSWORD: 'Harish@123'


JWT_TOKEN: 
    SECRET_KEY: '187a72e8b6cebae99cef77394522dcea'
    ALGORITHM: 'HS256'
    ACCESS_TOKEN_EXPIRE_MINUTES: 10